### ISSUE TITLE
Suggestion for the script

### ISSUE THREAD

**Issue by Zero3K** [nsmryan/make2ninja#1]
It should show the amount of source code files in the project instead of the one (that being the command that it runs) that it is currently showing.

**Comment by nsmryan** [comment]
I'm not sure what you are saying here. Could you give a little more detail, like what the difference in output might be?

**Comment by nsmryan** [comment]
I'll leave this open for a bit in case you have some more details on the suggestion.

**Comment by Zero3K** [comment]
![VirtualBox_ROSBE_05_06_2022_16_16_27](https://user-images.githubusercontent.com/6194332/172068977-2167a434-5646-4c97-94ef-0f91dee9258f.png)

**Comment by nsmryan** [comment]
I would consider accepting a PR, but like I said in the README, this is just a little experiment. If you use make2ninja and want something in particular I might accommodate it, but I still don't really understand what you are asking.
