### ISSUE TITLE
backquote on macOS

### ISSUE THREAD

**Issue by conversy** [nsmryan/make2ninja#4]
Hello,

this issue to signal that with `make` on macOS, in the regexps, a backquote should be used instead of a regular quote e.g.:
```
start_target_pattern = " *Considering target file `(.+)'."
```

instead of:
```
start_target_pattern = " *Considering target file '(.+)'."
```

I did not try to find an elegant solution to this problem, I just replaced them in case I run the script on macOS:
```
sed -i '' "s/\'(./\`(./" make2ninja.py
```

This issue might prove useful as a warning/reminder as long as no solution is devised.

**Comment by nsmryan** [comment]
It seems like it should be possible to use a character group like:
```
start_target_pattern = " *Considering target file [`'](.+)['']."
```

If you try this, let me know. I would not mind adding this little bit in if it helps macOS users.

**Comment by conversy** [comment]
(sorry, I haven't check this conversation for a long time)

good idea, and it works!

**Comment by nsmryan** [comment]
are you interested in making a PR for this change? I can make the change too, but I don't know exactly what you did to make it work.

**Comment by conversy** [comment]
I verified that your solution works, and created a PR: https://github.com/nsmryan/make2ninja/pull/6

**Comment by nsmryan** [comment]
Thank you- merged.
